### ISSUE TITLE
Bassa not working in windows 10 machine

### ISSUE THREAD

**Issue by SidDevelop** [scorelab/Bassa#409]
When I try and run Bassa in windows 10, the localhost opens and then when i enter the credentials, a mysql error pops-up and the python file indicates an error. Pls fix

**Comment by malithsen** [comment]
Please verify whether you have updated DBCon.py with your db credentials

**Comment by padamchopra** [comment]
@SidDevelop Try following instructions in this [wiki](https://github.com/scorelab/Bassa/wiki/Windows-Installation-Guide), or you can simply watch a video tutorial for it on [YouTube](https://www.youtube.com/watch?v=QAQaThaUOgE&feature=youtu.be)

**Comment by kmehant** [comment]
@SidDevelop Setting up Bassa is a complex process and I feel you haven't set up your Bassa API server and MySQL properly. Make sure you are running 5.7 version of MySQL. Given your credentials properly to Bassa API server so that it can talk to MySQL and allow you to log in. Update this file `DBCon.py` and for help check our **wikis** and **readme** and I am sure you will able to make it. I will close this issue. Please put more detailed errors in the **gitter** channel so that someone might help you with.
