### ISSUE TITLE
UI build fails

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#508]
I'm getting an error when trying to do a `gulp build` in `ui`  of branch `develop`

## Expected Behavior
It should generate the build artifacts into `dist` dir.

## Current Behavior
Gettign this error,
![image](https://user-images.githubusercontent.com/1391468/46573451-1563ef80-c9b3-11e8-9bfe-9553c88d38f1.png)

## Steps to Reproduce (for bugs)

1. checkout to `develop` branch
2. cd to `ui`
3. run `npm install`
4. run `gulp build`

## Your Environment
* Version used: v1.0.0
* Environment name and version: node v9.11.2
* Operating System and version:Ubuntu 18.04 LTS

**Comment by VibhorCodecianGupta** [comment]
@agentmilindu `gulp-uglify` can't minify any ES6 Javascript code written, which is the reason this error is thrown. The solution is to either change ES6 to ES5 (which is out of the window of course) or to use `gulp-uglify-es` or `gulp-babel`. I was able to make this work with `gulp-uglify-es` because babel plugin requires managing some peer dependencies too. PR coming in ASAP.

**Comment by agentmilindu** [comment]
@VibhorCodecianGupta Good catch! Can you fix it and send a PR?

**Comment by VibhorCodecianGupta** [comment]
@agentmilindu please review #512
